name: example-environment
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - json==2.0.9
  - re
  - pip
  - pip:
    - qgrid
    - pandas
    - getopt
    - os
    - sys
    - zipfile
